config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :posts do
	  resources :comments
	  resources :talks
	  resources :costs
	  resources :incomes
  end

end

app/models/talk.rb
class Talk < ActiveRecord::Base
	#validates :post_id, :presence => true
	#validates :body,    :presence => true
	belongs_to :post
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:show, :edit, :update, :destroy]

  # GET /talks
  # GET /talks.json
  def index
    @talks = Talk.all
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
  end

  # GET /talks/new
  def new
    @talk = Talk.new
  end

  # GET /talks/1/edit
  def edit
  end

  # POST /talks
  # POST /talks.json
  def create
    #@talk = Talk.new(talk_params)
    @post = Post.find(params[:post_id])
    @talk = @post.talks.create(talk_params)

    respond_to do |format|
      if @talk.save
        #format.html { redirect_to @talk, notice: 'Talk was successfully created.' }
        format.html { redirect_to @post, notice: 'Talk was successfully created.' }
        format.json { render :show, status: :created, location: @talk }
      else
        format.html { render :new }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talks/1
  # PATCH/PUT /talks/1.json
  def update
    respond_to do |format|
      if @talk.update(talk_params)
        format.html { redirect_to @talk, notice: 'Talk was successfully updated.' }
        format.json { render :show, status: :ok, location: @talk }
      else
        format.html { render :edit }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    @talk.destroy
    respond_to do |format|
      format.html { redirect_to talks_url, notice: 'Talk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talk
      @talk = Talk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talk_params
      params.require(:talk).permit(:post_id, :body)
    end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<h1>Editing Talk</h1>

<%= render 'form' %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Talks</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @talks.each do |talk| %>
      <tr>
        <td><%= talk.post_id %></td>
        <td><%= talk.body %></td>
        <td><%= link_to 'Show', talk %></td>
        <td><%= link_to 'Edit', edit_talk_path(talk) %></td>
        <td><%= link_to 'Destroy', talk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Talk', new_talk_path %>

app/views/talks/new.html.erb
<h1>New Talk</h1>

<%= render 'form' %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @talk.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @talk.body %>
</p>

<%= link_to 'Edit', edit_talk_path(@talk) %> |
<%= link_to 'Back', talks_path %>