config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :posts do
	  resources :comments
	  resources :talks
	  resources :costs
	  resources :incomes
  end

end

app/models/cost.rb
class Cost < ActiveRecord::Base
	belongs_to :post
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    #@cost = Cost.new(cost_params)
    @post = Post.find(params[:post_id])
    @cost = @post.costs.create(cost_params)

    respond_to do |format|
      if @cost.save
        #format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
	format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
	format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:post_id, :body, :money)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_cost.html.erb
<%= div_for cost do%>
	<p>
		<strong>Posted <%= time_ago_in_words(cost.created_at) %></strong><br />
		<%= h(cost.body) %>
	<p>
<% end %>

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :money %><br>
    <%= f.number_field :money %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/costs/create.js.erb
var new_cost = $("<%= escape_javascript(render(:partial => @cost))%>").hide();
$('#costs').prepend(new_cost);
$('#cost_<%= @cost.id %>').fadeIn('slow');
$('#new_cost')[0].reset();

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Costs</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th>Money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.post_id %></td>
        <td><%= cost.body %></td>
        <td><%= cost.money %></td>
        <td><%= link_to 'Show', cost %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost', new_cost_path %>

app/views/costs/new.html.erb
<h1>New Cost</h1>

<%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @cost.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @cost.body %>
</p>

<p>
  <strong>Money:</strong>
  <%= @cost.money %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>